#!/bin/sh

# Create user
niutil -create . /users/wired
niutil -createprop . /users/wired uid 120
niutil -createprop . /users/wired gid 1
niutil -createprop . /users/wired passwd "*"
niutil -createprop . /users/wired home "/var/empty"
niutil -createprop . /users/wired shell "/usr/bin/false"
niutil -createprop . /users/wired realname "Wired Server"
niutil -createprop . /users/wired expire 0
niutil -createprop . /users/wired change 0
niutil -createprop . /users/wired _writers_passwd wired

exit 0
